### ISSUE TITLE
for VATEX dataset

### ISSUE THREAD

**Issue by hello12345world** [yuqi657/ts2_net#1]
Sorry, I can't find the VATEX dataset in  [ArrowLuo/CLIP4Clip](https://github.com/ArrowLuo/CLIP4Clip). Could you tell me how can I get this dataset for this project.

**Comment by yuqi657** [comment]
Thanks for your attention. You can refer to https://eric-xw.github.io/vatex-website/download.html  and dataloader_vatex_retrieval.py to prepare VATEX dataset and annotation.

**Comment by LiuRicky** [comment]
> Sorry, I can't find the VATEX dataset in [ArrowLuo/CLIP4Clip](https://github.com/ArrowLuo/CLIP4Clip). Could you tell me how can I get this dataset for this project.

Thanks for your attention. You can refer to https://eric-xw.github.io/vatex-website/download.html and dataloader_vatex_retrieval.py to prepare VATEX dataset and annotation.

**Comment by yuqi657** [comment]
> Sorry, I can't find the VATEX dataset in [ArrowLuo/CLIP4Clip](https://github.com/ArrowLuo/CLIP4Clip). Could you tell me how can I get this dataset for this project.

**Comment by jianghaojun** [comment]
Get the split file from https://github.com/cshizhe/hgr_v2t.

**Comment by jianghaojun** [comment]
@yuqi657 It seems we need to download the video by ourself. How much storage space shoud we prepare to download this dataest?

**Comment by LiuRicky** [comment]
> 

It is around 100 G.

**Comment by jianghaojun** [comment]
@yuqi657 Thanks for your reply. Besides, is there a easy way to download these videos?
