### ISSUE TITLE
About VATEX dataset

### ISSUE THREAD

**Issue by Vincent-ZHQ** [yuqi657/ts2_net#11]
Thank you for the information you provided on the VATEX dataset.

With your provided information, I got the raw videos from the website of [VATEX](https://eric-xw.github.io/vatex-website/download.html) with the tool of yt-dlp (youtube-dl is not updated and it does not work for me). Also, I got the dataset splits methods from [hgr_v2t](https://github.com/cshizhe/hgr_v2t). 

However, I can only get 1335 video clips for the test set. It is different from the original setting (1500). May I ask how many videos you use in your final experiments? Could you please share your downloaded video clips with me?

I appreciate your help and my email is zouhq01@gmail.com

**Comment by LiuRicky** [comment]
We have 1500 test video clips. I have sent an email to you for details.

**Comment by zef1611** [comment]
> We have 1500 test video clips. I have sent an email to you for details.

Hi can I have this dataset since I find VATEX really hard to download and every link is die now. If possible can you send me the train and testset link of VATEX please.

I really appreciate your help and my email is [lehuy2316@gmail.com](mailto:lehuy2316@gmail.com)
