### ISSUE TITLE
About ActivityNet-Caption,  DiDeMo, LSMDC experiment's Detail

### ISSUE THREAD

**Issue by sssss99999** [yuqi657/ts2_net#9]
First of all, thank you for sharing your good research.
There are only MSRVTT and VATEX datasets training parameters in **scripts**, and ActivityNet,  DiDeMo, and LSMDC are not available. Can you provide them?

**Comment by yuqi657** [comment]
Thanks for your attention to our work.

The scripts of datasets you mentioned is the same as msrvtt and vatex. You can replace 
'--data_path ${DATA_PATH}/vatex_data \
--features_path ${DATA_PATH}/compressed_videos \
--output_dir ckpts/vatex \
--datatype vatex ' 
with the dataset you want to use.
Besides, if your data annotation is not suitable with specific dataloader, you may need to change dataloader_xxxx_retrieval.py

**Comment by LiuRicky** [comment]
> First of all, thank you for sharing your good research. There are only MSRVTT and VATEX datasets training parameters in **scripts**, and ActivityNet, DiDeMo, and LSMDC are not available. Can you provide them?

Thanks for your attention to our work.

The scripts of datasets you mentioned is the same as msrvtt and vatex. You can replace
'--data_path ${DATA_PATH}/vatex_data
--features_path ${DATA_PATH}/compressed_videos
--output_dir ckpts/vatex
--datatype vatex '
with the dataset you want to use.
Besides, if your data annotation is not suitable with specific dataloader, you may need to change dataloader_xxxx_retrieval.py
